version: "3.9"

services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=algorithms
    volumes:
      - .:/var/www/algorithms
      - ~/.composer/auth.json:/root/.composer/auth.json
      - ~/.aws:/root/.aws
    networks:
      - algorithms

networks:
  algorithms: